name: CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_ENV: production
      HUSKY: 0 # skip husky install in CI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Built-in pnpm cache (packageManager field present)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack
        run: corepack enable

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - name: Enable corepack and prepare pnpm
      #   run: |
      #     corepack enable
      #     pnpm --version

      # - name: Get pnpm store path
      #   id: pnpm-store
      #   run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # - name: Cache pnpm store
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.PNPM_STORE_PATH }}
      #     key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
      #     restore-keys: |
      #       pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run type-check

      - name: Build
        run: pnpm run build:ci

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dist
      #     path: dist
#   deploy:
#     name: Deploy to GitHub Pages
#     runs-on: ubuntu-latest
#     needs: build
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: dist
#           path: dist

#       - name: Deploy to gh-pages
#         uses: peaceiris/actions-gh-pages@v4
#         with:
#           publish_dir: ./dist
#           publish_branch: gh-pages
#           github_token: ${{ secrets.GITHUB_TOKEN }}
