name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types:
      - completed
  workflow_dispatch:

env:
  IMG_NAME: 'blog-react'
  TAG: 'latest'

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The CI workflow passed successfully'

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: on-success
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project version
        uses: saionaro/extract-package-version@v1.3.0
        id: package_ver

      - name: Set Date and Package Version
        run: |
          echo "Package version: ${{ steps.package_ver.outputs.version }}"
          echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: production
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.USERNAME }}/${{ env.IMG_NAME }}:${{ env.TAG }}
            ${{ env.USERNAME }}/${{ env.IMG_NAME }}:v${{ steps.package_ver.outputs.version }}
            ${{ env.USERNAME }}/${{ env.IMG_NAME }}:v${{ steps.package_ver.outputs.version }}-${{ env.NOW }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.USERNAME }}/${{ env.IMG_NAME }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
